/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#041539",
        "on-primary": "#ffffff",
        "primary-container": "#1b2a4e",
        "on-primary-container": "#8392bc",
        secondary: "#8e4e14",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffab69",
        "on-secondary-container": "#783d01",
        tertiary: "#001c10",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#003321",
        "on-tertiary-container": "#629f81",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        outline: "#75777f",
        "outline-variant": "#c5c6cf",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "2.5rem",
        gutter: "1.5rem",
        "container-max": "1280px",
        "margin-mobile": "1rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans Devanagari", "ui-sans-serif", "system-ui"],
        hindi: ["Noto Sans Devanagari", "sans-serif"],
        english: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
